### ISSUE TITLE
POST /api/notes should receive a new note to save on the request body, add it to the db.json file, and then return the new note to the client. You'll need to find a way to give each note a unique id when it's saved (look into npm packages that could do this for you).

### ISSUE THREAD

**Issue by roo116** [roo116/note-taker#11]

**Comment by roo116** [comment]
need to sort this error first.
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:2150:5)
    at createNewNote (/Users/chiphill/unc/repos/note-taker/server.js:17:6)
    at /Users/chiphill/unc/repos/note-taker/server.js:54:16
    at Layer.handle [as handle_request] (/Users/chiphill/unc/repos/note-taker/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/chiphill/unc/repos/note-taker/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/chiphill/unc/repos/note-taker/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/chiphill/unc/repos/note-taker/node_modules/express/lib/router/layer.js:95:5)
    at /Users/chiphill/unc/repos/note-taker/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/chiphill/unc/repos/note-taker/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/chiphill/unc/repos/note-taker/node_modules/express/lib/router/index.js:280:10)
